# Generated by Django 3.2.16 on 2023-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_card_cno_alter_manager_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
